env:
  seed: 1
  scene_id: 4     # 0 wasteland, 1 japanese street, 4 emptyforest in SR standalone
  num_envs: 16    # Important: same to batch size!
  num_threads: 16
  dataset_path: "/run/yopo_sim/"  # path of training dataset
  ply_path: "/run/yopo_sim/"      # path of the point could of training data

enable_multiple_scene : yes
multiple_scene_env:
  scene_count: 3
  scenes:
    scene_1:
      scene_name: dense_forest
      bounding_box: [20, 80, 11]
      bounding_box_origin: [-30, 20, 2.5]
      spacing: 4
    scene_2:
      scene_name: sparse_forest
      bounding_box: [20, 80, 11]
      bounding_box_origin: [-10, 20, 2.5]
      spacing: 6
    scene_3:
      scene_name: empty_forest
      bounding_box: [20, 80, 11]
      bounding_box_origin: [10, 20, 2.5]
      spacing: 8
  
unity:
  spawn_trees: true
  avg_tree_spacing: 4                 # average spacing between trees
  # larger than the position to generate the drone to ensure the completeness of the point cloud in edge.
  bounding_box: [80.0, 80.0, 11]      # spawn objects within this bounding box
  bounding_box_origin: [-10, 20, 2.5]
  pointcloud_resolution: 0.2
